### ISSUE TITLE
Standardize Resolvr Logos

### ISSUE THREAD

**Issue by BitcoinBrief** [Resolvr-io/resolvr.io#51]
Here's the current logo (but source components from Figma)

![](https://images.squarespace-cdn.com/content/v1/65395e3087238f2bcef5379f/86023213-c530-4f72-979f-4b902e2bb02e/resolvr+logo+title.png?format=1500w)

I'd like to see the logo in lowercase, as well.

Also, the Favicon in the browser tab is currently skewed/squished.

**Comment by utidon** [comment]
![Resolvr favicon 140 _140](https://github.com/Resolvr-io/resolvr.io/assets/81318863/f00950ac-1448-40cb-8f2b-5ecbe6189bd2)
![Resolvr Logo white](https://github.com/Resolvr-io/resolvr.io/assets/81318863/fb36512d-f66b-4470-8024-8502fe0c56b8)
![Resolvr Logo black](https://github.com/Resolvr-io/resolvr.io/assets/81318863/eb0cdc92-555a-4652-bd4a-db3773119c05)
[
![Resolvr Site logo](https://github.com/Resolvr-io/resolvr.io/assets/81318863/d57b648f-fe25-41f5-a653-da2970e23e9f)
](url)

Does this suffice?

**Comment by ChristianChiarulli** [comment]
I think the r should be lowercase as well but not sure

**Comment by BitcoinBrief** [comment]
> I think the r should be lowercase as well but not sure
 Try r lowercase.

**Comment by utidon** [comment]
**Updated logo and logotype without background**

I had to remove the extended slash in the logotype because they made everything lose balance
![Resolvr Logotype black](https://github.com/Resolvr-io/resolvr.io/assets/81318863/02cdaaa6-493c-4b58-805d-f86fd449f71d)
![Resolvr Logotype white](https://github.com/Resolvr-io/resolvr.io/assets/81318863/76f5046f-806a-407a-9782-3dfbf103e452)
![Resolvr Logo white](https://github.com/Resolvr-io/resolvr.io/assets/81318863/5e7300e7-892b-49a6-87f2-0abc4f7f2bec)
![Resolvr Logo black](https://github.com/Resolvr-io/resolvr.io/assets/81318863/379fdb61-c9f3-4020-bb8c-68445e8bda0b)
